[package]
name = "hib"
version = "1.0.0"
edition = "2021"
license-file = "LICENSE"
homepage = "https://github.com/AirOne01/hib"
repository = "https://github.com/AirOne01/hib"
readme = "README.md"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.2"
